"""add ab_test_runs cost_records webhook_deliveries unique_span_id

Revision ID: 3dd412a5fc4c
Revises: c5a53df4fc4e
Create Date: 2026-06-07 08:14:50.756109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd412a5fc4c'
down_revision: Union[str, Sequence[str], None] = 'c5a53df4fc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_test_runs',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('prompt_a', sa.Text(), nullable=False),
    sa.Column('prompt_b', sa.Text(), nullable=False),
    sa.Column('criteria_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('pass_rate_a', sa.Float(), nullable=True),
    sa.Column('pass_rate_b', sa.Float(), nullable=True),
    sa.Column('avg_score_a', sa.Float(), nullable=True),
    sa.Column('avg_score_b', sa.Float(), nullable=True),
    sa.Column('winner', sa.String(length=8), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_records',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('span_id', sa.String(length=12), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('alert_id', sa.String(length=12), nullable=True),
    sa.Column('project_id', sa.String(length=12), nullable=False),
    sa.Column('webhook_url', sa.String(length=2000), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.Float(), nullable=True),
    sa.Column('next_retry_at', sa.Float(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uq_spans_span_id', 'spans', ['span_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_spans_span_id', 'spans', type_='unique')
    op.drop_table('webhook_deliveries')
    op.drop_table('cost_records')
    op.drop_table('ab_test_runs')
    # ### end Alembic commands ###
