"""add ab_test_runs table

Revision ID: c5a53df4fc4e
Revises: 651529d2a92e
Create Date: 2026-05-30 19:22:08.214377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a53df4fc4e'
down_revision: Union[str, Sequence[str], None] = '651529d2a92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eval_results', sa.Column('confidence', sa.String(), nullable=True))
    op.add_column('eval_results', sa.Column('is_ambiguous', sa.Boolean(), nullable=True))
    op.add_column('eval_results', sa.Column('ci_lower', sa.Float(), nullable=True))
    op.add_column('eval_results', sa.Column('ci_upper', sa.Float(), nullable=True))
    op.add_column('eval_results', sa.Column('reference_match', sa.Float(), nullable=True))
    op.add_column('eval_results', sa.Column('factual_contradiction', sa.Boolean(), nullable=True))
    op.add_column('eval_results', sa.Column('improvement', sa.Text(), nullable=True))
    op.add_column('eval_results', sa.Column('task_type', sa.String(), nullable=True))
    op.add_column('eval_results', sa.Column('task_metrics_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eval_results', 'task_metrics_json')
    op.drop_column('eval_results', 'task_type')
    op.drop_column('eval_results', 'improvement')
    op.drop_column('eval_results', 'factual_contradiction')
    op.drop_column('eval_results', 'reference_match')
    op.drop_column('eval_results', 'ci_upper')
    op.drop_column('eval_results', 'ci_lower')
    op.drop_column('eval_results', 'is_ambiguous')
    op.drop_column('eval_results', 'confidence')
    # ### end Alembic commands ###
